<div class="login">
    <h2>
        Войдите используя форму
    </h2>

    <?php echo $this->tag->form("users/login"); ?>

    <div class="form-group">
        <label for="name">Имя:</label>
        <?php /** @var $form - object form*/ echo $form->render("name"); ?>
    </div>

    <br>

    <br>
    <div class="">
        <label for="password">
            Пароль:
        </label>


        <?php echo $form->render("password"); ?>
    </div>



    <br>
    <div>
        <?php echo $this->tag->submitButton(
            [
                "Войти",
                "class" => "btn btn-primary"
            ]
        ); ?>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>