<div class="register">
  <h2>
    Зарегиcтрируйтесь используя форму
  </h2>

  <?php echo $this->tag->form("users/register"); ?>

  <div class="form-group">
    <label for="name">Имя:</label>
    <?php /** @var $form - object form*/ echo $form->render("name"); ?>
  </div>

  <br>

  <div class="">
    <label for="email">
        E-Mail:
    </label>


    <?php echo $form->render("email"); ?>
  </div>


  <br>
  <div class="">
      <label for="password">
          Пароль:
      </label>


      <?php echo $form->render("password"); ?>
  </div>



  <br>
  <div>
      <?php echo $this->tag->submitButton(
              [
                  "Зарегистрироваться",
                  "class" => "btn btn-primary"
              ]
      ); ?>
  </div>
  <?php echo $this->tag->endForm(); ?>
</div>
