<div class="link">
  <h4 class="link-logout">
    <?php echo $this->tag->linkTo(
            [
                "users/userdelete",
                "Удалить профиль",
                "class" => "btn btn-danger"
            ]
    ); ?>
  </h4>
</div>

<div class="user">
  <h3 style="color: #1ab7ea">
    Профиль пользователя и его описание:
  </h3>

  <br>

  <h4 style="color: #00a65a">Имя пользователя:
    <?php /** @var $name - имя*/ echo $name; ?>
  </h4>

  <br>

  <h4 style="color: #00a65a">Описание пользователя:
    <br>
    <br>

    <h4 style="color: #aa00bb"><?php /** @var  $about - обо мне */ echo $about; ?><h4>

    <br>
    <br>

    <?php /** @var $user  - передаём параметр в запрос*/
    // Делаем проверку добавлял ли пользователь информацию о себе,
    // если добавлял выводим другую ссылку для редактирования
    if ($about === null) {
        echo $this->tag->linkTo(
            [
                "users/userabout/$name",
                "Добавить информацию обо мне",
                "class" => "btn btn-primary"

            ]
        );
    } else {
        echo $this->tag->linkTo(
            [
                "users/useredit/$name",
                "Редактировать информацию обо мне",
                "class" => "btn btn-primary"

            ]
        );
    } ?>


    <br>
    <br>
  </h4>

  <h4 style="color: #00a65a">Электронная почта пользователя:
    <?php /** @var $email - электронный адрес*/ echo $email; ?>
  </h4>

  <br>

  <h4>
    <?php echo $this->tag->linkTo(
            [
                "robots/add/$name",
                "Добавить робота",
                "class" => "btn btn-primary"
            ]
    ); ?>
  </h4>

  <br>

  <h4 style="color: #00a65a">Список ваших роботов:</h4>
  <br>
  <ul style="color: #00a7d0">
  <?php /** @var  $robots - names robots*/
  foreach ($robots as $robot) {
      echo "<li><h4>$robot->name - $robot->type - $robot->year</h4></li>" . "<br><br>";

      echo $this->tag->linkTo(
          [
              "robots/edit/$robot->id",
              "Редактировать робота",
              "class" => "btn btn-warning"
          ]
      );

      echo " ";

      echo $this->tag->linkTo(
              [
                "robots/delete/$robot->id",
                "Удалить робота",
                "class" => "btn btn-danger"
              ]
      );
  } ?>
  </ul>
</div>
