<div class="user-show">
  <h2>
    Заполните эту форму!
  </h2>

  <?php echo $this->tag->form("users/useradd"); ?>

  <div>
    <div>
      <label for="about">Обо мне:</label>
    </div>

      <?php /** @var $form - object form*/ echo $form->render("about"); ?>

  </div>

  <br>
  <div>
      <?php echo $this->tag->submitButton(
          [
              "Добавить",
              "class" => "btn btn-primary"
          ]
      ); ?>
  </div>
  <?php echo $this->tag->endForm(); ?>
</div>
